import os

Import('env')

localEnv = env.Clone()

project   = 'test-radio-at86rf215-tx'
extension = '.elf'

target = project + extension
source = [
	'main.cpp'
]

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'] + ['m'],
    LIBPATH = env['lib_path']
)

Return('main')
